export const large = [
	{
		title: "Season Sponsors",
		names: [
			"Casey Peterson",
			"Chadron State College",
			"Footprints, Your Birkenstock Store",
			"Security First Bank",
		],
	},
	{
		title: "Show Sponsors",
		names: [
			"Anne Armstrong Sellman",
			"Big Bat's",
			"Jeanine Mohr and Gary Mohr",
			"Susan Sehnert Stuart ",
			"WESTCO",
		],
	},
	{
		title: "$10,000+",
		names: ["Richard P. Kimmel & Laurine Kimmel Charitable Foundation"],
	},
	{
		title: "$5,000–$9,999",
		names: [
			"Nebraska Arts Council",
			"Bill and Virginia Coffee Family Foundation",
			"Ethel S. Abbott Charitable Foundation",
		],
	},
	{
		title: "$2,500–$4,999",
		names: [
			"Darold Newblom Foundation",
			"Mr. Karl Tegtemeyer",
			"Bertram and Patricia Witham Foundation",
		],
	},
	{
		title: "$1,000–$2,499",
		names: [
			"Bloom Flowers and Gifts",
			"Mr. and Mrs. Tim and Kari Gaswick",
			"Kelley Bean Company",
			"Mr. and Mrs. Jim and Amy Gardner",
			"Ms. Irene Hughes",
			"Ms. Helen Kent",
			"Mr. and Mrs. Jim and Nancy Kerr",
			"Martin Drug & Mercantile",
			"Mr. and Mrs. Bruce and Lyn Messersmith",
			"Doug and Keri Ohlson, In Memory of Ellee Ferebee",
			"Phillips F & T Inc.",
			"Mrs. Marge Rotherham",
			"Annie and Richard Sellman",
			"Mr. Franklin Tolstedt",
			"Ms. Janelle Visser",
			"Walmart Foundation",
			"Mr. and Mrs. Matt and Loni Watson",
			"Mr. and Mrs. Jon & Linda Wiley",
		],
	},
]

export const small = [
	{
		title: "$500–$999",
		names: [
			"Mr. and Mrs. David and Diana Bauerkemper",
			"Ms. Ann Burk",
			"Mobius",
			"Ms. Dena Paris",
			"Ms. Sandy Scofield and Mr. Bob Wickersham",
			"Ms. Kathy Soester and Ms. Linda Caylor",
			"Anonymous (1)",
		],
	},
	{
		title: "$250–$499",
		names: [
			"Mr. John Axtell",
			"Buchheit Precision",
			"Beguin Propane",
			"Delsing Farm and Ranch",
			"First National Bank of Gordon",
			"Ms. Samantha Grimes",
			"Hemingford Community Federal Credit Union",
			"Ms. Ann Hencey",
			"Ms. Barb Kendle",
			"Mr. and Mrs. Dennis and Kathie King",
			"Mr. and Mrs. Glen and Vicki Kotschwar",
			"Ms. Mary Lou Lecher",
			"Ms. Danielle Lecher",
			"Ms. Mary Lou Marshall",
			"Mr. and Mrs. Dave and Ali Redden",
			"Ms. Linda Roos",
			"Mr. Tom Schleff",
			"Ms. Ann Stephens",
			"Ms. Dee Wood",
			"Mr. and Mrs. Les and Marilyn Wright",
		],
	},
	{
		title: "$100–$249",
		names: [
			"Mr. and Mrs. David and Laura Batchelor",
			"Ms. Stephanie Baumgarten",
			"Mr. Mark Berge",
			"Mr. and Mrs. James and Kathy Bowers",
			"Ms. JoAnn Bowman",
			"Ms. Cindi Brinton",
			"Ms. Jo Buchheit",
			"Mrs. and Mr. Cheryl and Jerry Cassiday",
			"Mrs. Sandra Castek",
			"Clicks by Kim",
			"Mr. Paul Cutler",
			"Mr. Robert Delsing",
			"Mr. and Mrs. Don and Paige Denton",
			"Ms. Connie Dolezal",
			"Ms. Donna Engel",
			"Dr. and Mrs. Jake and Em Ezell",
			"Mr. and Mrs. Guy Fish",
			"Ms. Karen Foote",
			"Ms. Lori Fritz",
			"Green Acres",
			"Ms. Joyce Hammer",
			"Mr. and Ms. Blake and Ali Hansen",
			"Mr. Derek Harris",
			"Mr. Jason Hawk",
			"Mr. Bill Huntington",
			"Mr. Ted Jaery",
			"Mr. and Mrs. Joni and Donald Jespersen",
			"Mr. Randy Kane",
			"Ms. Heidi King",
			"Mr. David Mattson",
			"Mr. Jerry McLain",
			"Mr. TJ Moore",
			"Music and Dramatic Club of Gordon",
			"Mr. John Nickens",
			"Mr. and Ms. Kevin and Jo Olesky",
			"Mr. Glen Price",
			"Ms. Andi Rising",
			"Ms. Joyce Ruse",
			"Mr. and Mrs. Tom and Dania Schleff",
			"Ms. Joyce Sekutera",
			"Mr. and Mrs. Butch And Gail Sellman",
			"Mr. Douglas Shaver",
			"Ms. Connie Shell",
			"Mr. and Mrs. Nathan and Brooke Smith",
			"Mr. and Mrs. Brian and Sara Taylor",
			"Mr. and Mrs. Ted and Dana Tewahade",
			"Mr. and Mrs. Grover and Vicki Thompson",
			"Mr. Albion Visser",
			"Mr. and Mrs. Robert & Jane Wahlstrom",
			"Mr. and Mrs. Rod and Sheri Wallace",
			"Mr. and Mrs. Brad Williams",
			"Mr. and Mrs. Kael and Stacy Wood",
			"Mr. Mitch Wright",
		],
	},
]
