export const special = [
	{
		title: "$25,000+",
		names: ["Dawes County Travel Board"],
	},
	{
		title: "$10,000+",
		names: ["Oregon Trail Community Foundation"],
	},
	{
		title: "$2,500+",
		names: [
			"Bill and Virginia Coffee Family Foundation",
			"Security First Bank",
		],
	},
]

export const large = [
	{
		title: "Season Sponsors",
		names: ["Casey Peterson", "Chadron State College", "Security First Bank"],
	},
	{
		title: "Show Sponsors",
		names: [
			"Footprints, Your Birkenstock Store",
			"Anne Armstrong Sellman",
			"Janelle Visser and Jeanine Mohr",
			"Susan Sehnert Stuart",
			"WESTCO",
		],
	},
	{
		title: "$5,000+",
		names: [
			"Richard P. Kimmel and Laurine Kimmel Charitable Foundation",
			"Nebraska Arts Council",
			"Linda and Jon Steven Wiley",
		],
	},
	{
		title: "$2,500+",
		names: ["Darold Newblom Foundation"],
	},
	{
		title: "$1,000+",
		names: [
			"Big Bats",
			"Jim and Amy Gardner",
			"H&R Block of Chadron",
			"Harris Sales Company",
			"Jack Isaacs",
			"Kelley Bean Company",
			"Jim and Nancy Kerr",
			"Martin Drug & Mercantile",
			"Phillips F & T Inc.",
			"Marge Rotherham",
			"Annie and Richard Sellman",
			"Walmart Foundation",
			"Bertram and Patricia Witham Foundation",
		],
	},
]

export const small = [
	{
		title: "$500+",
		names: [
			"David and Diana Bauerkemper",
			"James and Kathy Bowers",
			"Blake Hansen",
			"Hardrock Blasting",
			"JAV Enterprises LLC",
			"Mobius Communications",
			"Nebraska Bank",
			"Dena Paris",
			"Platte Valley Bank",
			"Troy Unzicker",
			"Anonymous (1)",
		],
	},
	{
		title: "$250+",
		names: [
			"Beguin Propane",
			"Gary and Dixie Blundell",
			"Buchheit Precision",
			"Delsing Farms",
			"John and Nancy Erickson",
			"Farmers Coop Elevator Company",
			"Merlyn* and Karleen Gramberg",
			"Hardrock Blasting",
			"Hemingford Community Federal Credit Union",
			"Dennis and Kathie King",
			"Steve and Kathy Klaes",
			"Glen and Vicky Kotschwar",
			"Curt and Mary Lou Lecher",
			"Patrick McMahon",
			"Kathy Orloski",
			"Dave and Ali Redden",
			"Joan and Clark Scarboro",
			"Tom Schleff",
			"Table Top Meats Inc.",
			"Terrance Terrell",
		],
	},
	{
		title: "$100+",
		names: [
			"Von Bartlett",
			"David and Laura Batchelor",
			"Mark Berge",
			"Jo Buccheit",
			"Doris Burton",
			"Cheryl and Jerry Cassiday",
			"Chadron Lawn Care",
			"Crawford Livestock Market",
			"Paul Cutler",
			"Robert Delsing",
			"Donna Engle",
			"Farmers Coop Elevator Company",
			"Guy Fish",
			"Florence Foldenauer",
			"Tim and Kari Gaswick",
			"Darold German",
			"Bev Hanks",
			"Jason Hawk",
			"Alex and Brittany Helmbrecht",
			"Ann Hencey",
			"Rick and Misty Hickstein",
			"Cindi Jacobsen-Brinton",
			"Joni and Donald Jespersen",
			"Randy Kane",
			"Barb Kendle",
			"Greta Kickland",
			"Danielle and Clint Lecher",
			"Mary Lou Marshall",
			"David and Jean Mattson",
			"TJ Moore",
			"Music and Dramatic Club of Gordon",
			"Doug and Keri Ohlson",
			"Johannah Oleksy",
			"Jill PaoPao",
			"Bradley Peterson",
			"Glen Price",
			"Kim Reichert",
			"Joyce Ruse",
			"Sue Rusie",
			"Nancy Sayer",
			"Sandra Scofield",
			"Wally Seiler",
			"Joyce Sekutera",
			"Douglas Shaver",
			"Nathan Smith",
			"Dana Sorensen",
			"Ted and Dana Tewahade",
			"Linda Thayer",
			"Russ and Susan Trinter",
			"Ted Vastine",
			"Robert and Jane Wahlstrom",
			"Brad and Sue Williams",
			"Dee Wood",
			"Les Wright",
		],
	},
]
