import { join } from "node:path"

export const SCHEMA_VERSION = 1 as const
// Bump when publisher logic can change generated bytes or Picture metadata.
export const GENERATOR_REVISION = 1 as const
export const CURRENT_SEASON = 2027 as const
export const STORE_PREFIX = `historical-images/v${SCHEMA_VERSION}`
export const LOCK_PATH = "historical-images/publication.v1.json"
export const GENERATED_MAP_PATH = "src/generated/historical-images/pictures.ts"
export const STATIC_ASSET_ROOT = "static/_app/immutable/assets"
export const CACHE_ROOT = ".cache/historical-images"
export const TRUSTED_PUBLISH_COMMAND = "pnpm images:historical:publish"

export const imageExtensions = new Set([
	".avif",
	".gif",
	".heif",
	".jpeg",
	".jpg",
	".png",
	".tiff",
	".webp",
	".svg",
])

export const profiles = {
	people: {
		id: "people-400-800",
		widths: [400, 800],
		withoutEnlargement: true,
	},
	season: {
		id: "season-500-1000-1500",
		widths: [500, 1000, 1500],
		withoutEnlargement: true,
	},
	raffle: {
		id: "raffle-default-1x-2x",
		widths: [1, 2],
		withoutEnlargement: false,
	},
} as const

export function objectName(sha256: string): string {
	return `${STORE_PREFIX}/objects/${sha256}`
}

export function manifestName(sha256: string): string {
	return `${STORE_PREFIX}/manifests/${sha256}.json`
}

export function latestName(): string {
	return `${STORE_PREFIX}/latest.json`
}

export function cacheObjectPath(root: string, sha256: string): string {
	return join(root, CACHE_ROOT, "objects", sha256)
}
