import type { HistoricalManifest, HistoricalSource } from "./schema"

export function generatedMap(manifest: HistoricalManifest): string {
	const maps: Record<string, Record<string, HistoricalSource["picture"]>> = {}
	for (const source of manifest.sources) {
		if (!source.collection || !source.logicalPath)
			throw new Error(
				`Manifest source lacks generated metadata mapping: ${source.path}`,
			)
		;(maps[source.collection] ??= {})[source.logicalPath] = source.picture
	}
	return `// Generated by pnpm images:historical:generate. Do not edit.\nimport type { Picture } from "$helpers/enhancedImg"\n\n${Object.entries(
		maps,
	)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(
			([name, pictures]) =>
				`// prettier-ignore\nexport const ${name} = ${JSON.stringify(pictures)} as const satisfies Record<string, Picture>`,
		)
		.join("\n")}\n`
}
